"use client"

import { motion } from "framer-motion"
import Link from "next/link"

export default function HowItWorks() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-teal-50 via-emerald-100 to-blue-200">
      <div className="max-w-4xl mx-auto p-8">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="space-y-8"
        >
           <h1 className="text-4xl font-bold text-teal-700 text-center mb-8">How It Works</h1>

<section className="bg-white/60 backdrop-blur-sm rounded-xl p-8 shadow-lg border border-teal-200">
  <div className="flex justify-center items-center">
    <div className="w-[720px] h-[480px]">
      <iframe 
        width="720"
        height="480"
        className="rounded-lg shadow-lg"
        src="https://www.youtube.com/embed/LJ3jUXtnFGA?si=Csez2HSKaaUszk-j" 
        title="YouTube video player" 
        frameBorder="0" 
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
        referrerPolicy="strict-origin-when-cross-origin" 
        allowFullScreen
      ></iframe>
    </div>
  </div>
  <div className="mt-8 prose prose-teal max-w-none">
              <p className="text-gray-700 leading-relaxed">
                Alright, here's a simplified explanation of your Orca Whirlpool project & fee distribution concept:
              </p>
              
              <p className="text-gray-700 leading-relaxed mt-4">
                When the Orca Whirlpool configuration system isup and running, here's how it will work:
              </p>

              <ul className="list-disc pl-6 mt-4 space-y-3 text-gray-700">
                <li>
                  <strong>Orca Protocol Fees:</strong> Fees generated from the protocol will go not only to the specific pools involved in successful prediction markets (which win rounds through swaps), but 10% of all protocol fees will also go directly to $ORCA token holders. This adds a valuable utility to $ORCA, rewarding holders and making the token more attractive.
                </li>
                <li>
                  <strong>App Functionality:</strong> This app functions as an automated trading tool within the Orca ecosystem. When users interact with it, they are essentially "aping into" (or investing in) specific pools. Similar to platforms like Bullx or Photon, the app automatically trades and optimizes all your Orca positions. It does this on the backend using a unique key generated by the app to manage your assets effectively.
                </li>
                <li>
                  <strong>High Yield Potential:</strong> The idea is that this tool will generate high annual returns (potentially in the millions of percent, theoretically speaking) by efficiently managing positions and capturing trading fees.
                </li>
                <li>
                  <strong>Fee Distribution:</strong>
                  <ul className="list-disc pl-6 mt-2 space-y-2">
                    <li>10% of fees are returned to $ORCA token holders, enhancing the token's appeal.</li>
                    <li>90% of fees are allocated to emerging prediction market pools, such as those in a Polymarket-style system. This means new or smaller pools will receive a portion of these accumulated fees based on their total value locked (TVL), helping to grow their resources over time.</li>
                  </ul>
                </li>
              </ul>

              <p className="text-gray-700 leading-relaxed mt-4">
                In essence, as more people use this system, they fuel both their own pool investments and help bolster the Orca ecosystem, creating a dynamic and rewarding cycle.
              </p>
            </div>
          </section>

          <div className="text-center">
            <Link 
              href="/"
              className="inline-block bg-teal-600 text-white px-6 py-3 rounded-full hover:bg-teal-700 transition-colors"
            >
              Back to Home
            </Link>
          </div>
        </motion.div>
      </div>
    </div>
  )
} 